### ISSUE TITLE
Readme links

### ISSUE THREAD

**Issue by CinnamonFreak** [ElderDrivers/EdXposed-Magisk#1]
Links for downloading EdXposed and EdXposed Manager in the Readme section Usage section are wrong.

The link for EdXposed is [https://github.com/Elder-Drivers/EdXposed/releases](https://github.com/Elder-Drivers/EdXposed/releases) and it should be [https://github.com/ElderDrivers/EdXposed/releases](https://github.com/ElderDrivers/EdXposed/releases)

**Comment by solohsu** [comment]
Thanks. Corrected with 4bb7e8cb569ee00bd50225f62fcc4dce4e2868b1.
